services:
  db:
    image: postgres:16.3
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DATASOURCE_USER}
      - POSTGRES_USER=${DATASOURCE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file: .env
    environment:
      - PGADMIN_LISTEN_PORT=8082
      - PGADMIN_DEFAULT_EMAIL=${DEFAULT_PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DEFAULT_PG_ADMIN_PASSWORD}
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres:
