services:
  server:
    build:
      context: .
    env_file: .env.docker
    ports:
      - 8090:8090
    networks:
      - app
    depends_on:
      - db
      - mailhog
      - rabbitmq


  db:
    image: postgres:16.3
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DATASOURCE_USER}
      - POSTGRES_USER=${DATASOURCE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file: .env
    environment:
      - PGADMIN_LISTEN_PORT=8082
      - PGADMIN_DEFAULT_EMAIL=${DEFAULT_PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DEFAULT_PG_ADMIN_PASSWORD}
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - app

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app

  rabbitmq:
    image: rabbitmq:3.13-management
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15671:15671"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres:
  rabbitmq:
